### ISSUE TITLE
Update Devices

### ISSUE THREAD

**Issue by benjamincash89** [meraki/dashboard-api-ansible#14]
Would it be possible for a plugin whereby updating the device can be achieved? Similar to that of the cisco.meraki.meraki_device module from the API dashboard.devices.updateDevice?

**Comment by benjamincash89** [comment]
I'm looking to update an MX with name information as well as tags which is similar to the legacy one mentioned above. That it allows me to apply device specific information against a device by serial as well as claim it. I'm already using cisco.meraki.networks_devices_claim to claim devices but i'm looking to also name the device once it's been claimed against a network.

**Comment by obrigg** [comment]
Got it.
Kindly try looking at [cisco.meraki.devices](https://galaxy.ansible.com/ui/repo/published/cisco/meraki/content/module/devices/)
