### ISSUE TITLE
Module `networks_devices_claim_vmx` got unexpected keyword argument network_id

### ISSUE THREAD

**Issue by briansak** [meraki/dashboard-api-ansible#19]
I received this error when trying to claim a small vMX device into a newly created network. 

"Unexpected failure during module execution: Networks.vmxNetworkDevicesClaim() got an unexpected keyword argument 'network_id'", "stdout": ""}

This might be related to the this issue which also references network_id.
https://github.com/meraki/dashboard-api-ansible/issues/18

**Comment by obrigg** [comment]
Hi Brian,
Thanks for reaching out. The two are related.
There is currently an issue with Ansible Galaxy preventing us from pushing an update. We'll fix it as soon as we can push an update.

FYI @fmunozmiranda.

**Comment by fmunozmiranda** [comment]
Hi @briansak , please try it with v2.16.10, and let us know if it works now for you.

**Comment by briansak** [comment]
Yes, with v2.16.10 (and 2.16.11) this is working as expected.
