### ISSUE TITLE
2.15.1 modules not working in 2.15.3

### ISSUE THREAD

**Issue by chaudharyatulphogat** [meraki/dashboard-api-ansible#2]
We have used 2.15.1 modules (e.g. meraki_vlan, cisco.meraki.meraki_mx_l2_interface etc) extensively and sudden disappear of these modules in 2.15.3 causing a lot of trouble. Moreover, even if decide to stay on 2.15.1, we can't do any further modification because the documentation has been removed. 

Is it possible to keep all previous modules in 2.15.3 or later?  So, we can keep using old modules and get benefits of new modules too?

**Comment by obrigg** [comment]
For the time being, v2.16.2 has backward compatibility with the previous modules. The documentation includes the previous modules too.
However, I would suggest that you start migrating playbooks to leverage the new modules.

**Comment by fmunozmiranda** [comment]
Hi @chaudharyatulphogat as @obrigg  says, old modules are available too. If you have some problem, you could say us, but as @obrigg suggests it is better if you start migrating playbooks to leverage the new modules.

Here you can see the equivalents of old modules:
https://github.com/meraki/dashboard-api-ansible/blob/main/meta/runtime.yml

**Comment by chaudharyatulphogat** [comment]
Hi @obrigg @fmunozmiranda, Thanks for your response. I along with my other colleagues upgraded to 2.15.3 and old modules were not working anymore. These modules' documentation is also not available now. Please find below error which we get while accessing cisco.meraki.meraki_mx_vlan module. 

`Missing documentation or could not parse documentation: cisco.meraki.meraki_mx_vlan did not contain a DOCUMENTATION attribute (/tmp/tmpmp0hu6uv/installed/ansible_collections/cisco/meraki/plugins/modules/meraki_mx_vlan.py). Unable to parse documentation in python file '/tmp/tmpmp0hu6uv/installed/ansible_collections/cisco/meraki/plugins/modules/meraki_mx_vlan.py': while parsing a block mapping
  in "<unicode string>", line 3, column 1
did not find expected key
  in "<unicode string>", line 60, column 3. while parsing a block mapping
  in "<unicode string>", line 3, column 1
did not find expected key
  in "<unicode string>", line 60, column 3`


It will take weeks of efforts for us to migrate to new playbook which doesn't seem to be a feasible option now. 

As I understand, old modules are expected to work but not working in 2.15.3. Do you plan to permanently remove the old modules in upcoming versions?

**Comment by fmunozmiranda** [comment]
https://meraki.github.io/dashboard-api-ansible/v2.16.2/plugins/index.html#plugin-index

Here you can see all documentation about that module, in v2.16.2, @chaudharyatulphogat

**Comment by fmunozmiranda** [comment]
@chaudharyatulphogat yes, old modules are going to be removed in v3.0.0

**Comment by fmunozmiranda** [comment]
Closed due inactivity.
