### ISSUE TITLE
Not able to update Meraki Access Point with new name

### ISSUE THREAD

**Issue by irvswirve** [meraki/dashboard-api-ansible#20]
using cisco.meraki.networks to update Meraki Access, and it does not allow me to add the serial of the AP i want to update.
Can you please assist?
![Issues](https://github.com/meraki/dashboard-api-ansible/assets/69480487/6a5bbd23-bdcb-4c50-af4f-1fec82b8bb21)
can you please assist
my email addy is irvswirve@gmail.com

**Comment by fmunozmiranda** [comment]
Hi @irvswirv, in Meraki's API documentation, I can't see `serial` parameter included.
https://developer.cisco.com/meraki/api/create-organization-network/

@obrigg Could it be an error in the documentation?

**Comment by obrigg** [comment]
Hi @irvswirve,
The name of the task "configure access point" make me wonder whether you're using the right module.
What are you trying to achieve?

**Comment by irvswirve** [comment]
@obrigg I am trying to rename the Meraki Access Point. Also could I use Ansible to do a Bulk renaming of Access Points?
Please advise

**Comment by obrigg** [comment]
That makes more sense. You're looking for the _updateDevice_ operation that maps to the [cisco.meraki.devices](https://galaxy.ansible.com/ui/repo/published/cisco/meraki/content/module/devices/) module.

**Comment by irvswirve** [comment]
Correct yes! so updateDevice operation is under the cisco.meraki.devices module? Correct?

**Comment by obrigg** [comment]
Correct.

**Comment by irvswirve** [comment]
Ok let me work on that and update this thread with my progress......Truly appreciate the response, If i get this right, this will help my team immensely...So stay tuned...lol

**Comment by irvswirve** [comment]
is this the correct ansible document i am using: https://docs.ansible.com/ansible/latest/collections/cisco/meraki/index.html

**Comment by irvswirve** [comment]
when checking on that module, i see this when going to https://docs.ansible.com/ansible/latest/collections/cisco/meraki/devices_module.html#ansible-collections-cisco-meraki-devices-module
![Screenshot 2023-10-26 133745](https://github.com/meraki/dashboard-api-ansible/assets/69480487/b116cab8-46a4-4abf-86e5-98ee38282774)

**Comment by irvswirve** [comment]
Also in Visual Studio Code, under cisco.meraki.devices I do not see updateDevice
![Screenshot 2023-10-26 no updateDevice](https://github.com/meraki/dashboard-api-ansible/assets/69480487/52267139-2e5c-45ee-9913-68b134c4f683)

**Comment by obrigg** [comment]
It looks outdated, @fmunozmiranda will you be able to take a look why is it showing 2.16.5?
@irvswirve, can you try the link I mentioned above?
(devices, not devices_up)

**Comment by irvswirve** [comment]
I am able to access https://galaxy.ansible.com/ui/repo/published/cisco/meraki/content/module/devices/
Is this what i should use?

**Comment by irvswirve** [comment]
so I should be on Ansible Version 2.16.10 and not 2.15.5?

**Comment by irvswirve** [comment]
I am so lost now

**Comment by obrigg** [comment]
1. The Ansible docs link you used **should** work. This is probably temporary.
2. The fixes between 2.16.5 and 2.16.10 shouldn't affect this specific module. 
3. I mentioned it as the Galaxy site is showing 2.16.10 documentation while the docs site is showing 2.16.5 - clearly not up to date.

**Comment by irvswirve** [comment]
i used the switch_ports and that works well....just trying to automate renaming Meraki Access Points and Meraki Switches

**Comment by obrigg** [comment]
You're almost there :-)

This should get you there:
```
- name: Update device name
  cisco.meraki.devices:
    name: My AP
    serial: Q234-ABCD-5678
```

**Comment by irvswirve** [comment]
let me try that now

**Comment by irvswirve** [comment]
It does not give me an error, it goes through, but i get this
PLAY RECAP **********************************************************************************************************************************************************************
meraki_server              : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by irvswirve** [comment]
it goes through  ok but nothing changes

**Comment by irvswirve** [comment]
anychance for a webex or TEAMS to assist me?

**Comment by obrigg** [comment]
Let me check that. I'll update soon.

**Comment by obrigg** [comment]
It was a sneaky one... kindly update to 2.16.12, and try it again, please.
`ansible-galaxy collection install cisco.meraki -f`

**Comment by irvswirve** [comment]
after updating do I run this again
- name: Update device name
  cisco.meraki.devices:
    name: My AP
    serial: Q234-ABCD-5678

**Comment by irvswirve** [comment]
That fixed it! Waht was the Issue?? @obrigg Thank You So much!!!! I will be testing out the other modules so I can easily deploy and Standardize Meraki Deployments

**Comment by obrigg** [comment]
Thank @fmunozmiranda :-) 
Good luck! Let us know if you encounter any other issues.

**Comment by irvswirve** [comment]
I will do! You guys are awesome and thank so much for been responsive!

**Comment by irvswirve** [comment]
Which module would I use to configure static IP addresses on the Switches and Access Points?

**Comment by irvswirve** [comment]
Should I open up a new ticket for issue with assigning static IP addresses?

**Comment by irvswirve** [comment]
Please let me know.......currently using cisco.meraki.networks_wireless_settings to assign static IP addresses to devices with no luck

**Comment by obrigg** [comment]
It should be `cisco.meraki.devices_management_interface`.
The easiest way to find the module you're looking for is through our [API Documentation](meraki.io/api). 
Once you found the operation, it's path will suggest the name of the relevant module. For example, the operation for [Network Switch Settings](https://developer.cisco.com/meraki/api-v1/update-network-switch-settings/) has the following URL: /networks/{networkId}/switch/settings, therefore its module is called cisco.meraki.networks_switch_settings.

The operation for [Device Camera Video Settings](https://developer.cisco.com/meraki/api-v1/update-device-camera-video-settings/) has the following URL: /devices/{serial}/camera/video/settings, therefore its module is called cisco.meraki.devices_camera_video_settings.

The operation for [Get Organization Admins](https://developer.cisco.com/meraki/api-v1/get-organization-admins/) has the following URL: /organizations/{organizationId}/admins, therefore its module is called cisco.meraki.organizations_admins_info and the module for updating admins is called cisco.meraki.organizations_admins.

**Comment by obrigg** [comment]
You can try out the [DevNet Learning Lab](https://developer.cisco.com/learning/labs/meraki-dashboard-ansible/introduction/) we created to help get people started.

**Comment by irvswirve** [comment]
Yeah i have gone through that already. ok I will be going through as you stated

**Comment by irvswirve** [comment]
I followed your guidance, and I was able to do quite a bit. Unfortunately, I am trying to discover the networks within an Organization but with no luck. Found the documentation at this link: https://developer.cisco.com/meraki/api-v1/get-organization-networks/ , but I dont see any cisco.meraki.organizations_networks module on the ansible doc...could you please assist? I only see cisco.meraki.organizations_networks_combine

**Comment by obrigg** [comment]
`cisco.meraki.networks_info`
https://galaxy.ansible.com/ui/repo/published/cisco/meraki/content/module/networks_info/

**Comment by irvswirve** [comment]
Thanks for the quick response......will check on it

**Comment by fmunozmiranda** [comment]
Closed due original problem fixed.
