### ISSUE TITLE
cisco.meraki.devices - missing 1 required positional argument: 'organizationId'

### ISSUE THREAD

**Issue by benjamincash89** [meraki/dashboard-api-ansible#25]
When executing - name: Set MX Name
  cisco.meraki.devices:
    meraki_api_key: "{{ api_key }}"
    state: present
    name: "{{ name }}"
    serial: "{{ mx_serial }}"

I receive the error below, which makes it appears it's not passing the organization ID though it's not an input parameter?

Error:  An error occured when executing operation.The error was: devices, getDevice - 404 Not Found, please wait a minute if the key or org was just newly created.
Error:  Organizations.getOrganizationDevices() missing 1 required positional argument: 'organizationId'
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [9001_be]: FAILED! => {"changed": false, "msg": "Object does not exists, plugin only has update"}

**Comment by obrigg** [comment]
Hi @benjamincash89 Benjamin,
Can you kindly check if the MX is associated with a network, or just "floating" in the organization?
You won't be able to change the name of the device while it's not associated with a network (this behavior is not specific to Ansible but the API call itself).

**Comment by benjamincash89** [comment]
Thanks for the pointer. I've gone back and revisited it and seems fine now. There was a MX assigned but not sure why I got that output previously as it's all good now. Thanks! 👍
