### ISSUE TITLE
No getNetworkClients API call equivalent module?

### ISSUE THREAD

**Issue by MrShed** [meraki/dashboard-api-ansible#30]
Sorry unsure if an issue is right, but just really checking that I'm right in saying that there's no module that gives the same functionality of the getNetworkClients endpoint (https://developer.cisco.com/meraki/api/get-network-clients/)?

I'd have thought I wouldn't be the only one with big use cases for this, if any chance this could be added would be amazing...!

**Comment by fmunozmiranda** [comment]
@MrShed `network_clients_info` was changed to use `getNetworkClients`  and `network_client_info` was added to still having `getNetworkClient` function.

**Comment by fmunozmiranda** [comment]
https://meraki.github.io/dashboard-api-ansible/main/plugins/networks_clients_info_module.html#ansible-collections-cisco-meraki-networks-clients-info-module

https://meraki.github.io/dashboard-api-ansible/main/plugins/networks_client_info_module.html#ansible-collections-cisco-meraki-networks-client-info-module

**Comment by MrShed** [comment]
@fmunozmiranda  - can't tell you how excited I am about this! Thank you :)

**Comment by MrShed** [comment]
Just to feed back in, this works a treat 🥇 thanks again :)

**Comment by MrShed** [comment]
If I may ask a total aside (this isn't related to the issue, just wondered if anyone may know) - is there any way to retrieve DHCP clients, or retrieve info as to whether a client is a DHCP client or not? Can't find anything in  API docs so I presume not but..!

**Comment by obrigg** [comment]
I do not believe that functionality exists today. You can ask for it through the "provide feedback" button on the Meraki Dashboard. It would help to understand the use-case and how you'd use the data.
