### ISSUE TITLE
Unable to set Syslog Servers for network - only Update supported

### ISSUE THREAD

**Issue by etamminga** [meraki/dashboard-api-ansible#32]
Hello,

while deploying a new network via Ansible, the task:

- name: Configure Network Syslog Settings
  cisco.meraki.networks_syslog_servers:
    meraki_api_key: "{{ meraki_api_key }}"
    meraki_suppress_logging: false
    state: present
    networkId: "{{ meraki_network_id }}"
    servers: 
      - host: "10.100.100.100"
        port: 514
        roles: 
          - Wireless event log
  register: result

The task fails with message: fatal: [localhost]: FAILED! => {"changed": false, "msg": "Object does not exists, plugin only has update"}

the same call succeeds when we've prepared the network via dashboard with a different Syslog server. this task successfully replaces the configuration but is not able to set it when no syslog servers exist prior to execution of this task

python library: meraki-1.39.0
ansible collection cisco.meraki  2.16.14
ansible version: 2.15.6

Regards,
Erik

**Comment by obrigg** [comment]
Hello Erik,
The syslogServer API endpoint has `GET` and `PUT` operations, which explains what you described.
I do not remember seeing any requests for this operation. If you can contact your Cisco/Meraki account team and ask them to submit this as a feature request - the team will be able to evaluate and address it.

Regards,
Oren.

**Comment by obrigg** [comment]
I take that back. Let me get back to you.

**Comment by fmunozmiranda** [comment]
Hi, @etamminga , The module was corrected to work like the PUT operation of the API.

**Comment by fmunozmiranda** [comment]
Please try it with last cisco.meraki version.

**Comment by etamminga** [comment]
:) It works, thank you!

**Comment by fabepach** [comment]
Hello. I am having the same issue as described. Which version of cisco.meraki should I install to resolve this issue?

Thank you.

**Comment by obrigg** [comment]
Kindly try version 2.17.2 of the collection.

**Comment by fabepach** [comment]
Hello again, no luck. Seems that this module is not working as the others for me. See the code below and the output. The variables such as meraki_action are usually already pre-filled and now seem to be empty. Thank you.

tasks:
    - name: Update syslog settings
      cisco.meraki.networks_syslog_servers:
        meraki_api_key: "{{ my_key }}"
        meraki_suppress_logging: true
        state: present
        networkId: "{{ networkId }}"
        servers:
        - host: 1.2.3.4
          port: 443
          roles:
          - URLs
      delegate_to: localhost
      register: result
Output
task path: /etc/ansible/scratch2.yml:14
Read vars_file './group_vars/credentials.yml'
The full traceback is:
NoneType: None
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": [
        "state. Supported parameters include: meraki_action_batch_retry_wait_time, meraki_api_key, meraki_base_url, meraki_be_geo_id, meraki_certificate_path, meraki_inherit_logging_config, meraki_log_file_prefix, meraki_log_path, meraki_maximum_retries, meraki_nginx_429_retry_wait_time, meraki_output_log, meraki_print_console, meraki_requests_proxy, meraki_retry_4xx_error, meraki_retry_4xx_error_wait_time, meraki_simulate, meraki_single_request_timeout, meraki_suppress_logging, meraki_use_iterator_for_get_pages, meraki_wait_on_rate_limit, networkId, servers."
    ]
}
Ansible core 2.16.2
python version 3.10.12
cisco.meraki 2.17.2

**Comment by obrigg** [comment]
Can you share the playbook in a code block? I have a feeling there is one tab too many on the `delegate_to: localhost` line.

The following works for me:
```
  - name: Syslog servers
    cisco.meraki.networks_syslog_servers:
      networkId: "{{ networkId }}"
      servers:
      - host: 1.2.3.4
        port: 443
        roles:
        - Wireless event log
        - URLs
    delegate_to: localhost
```

**Comment by fabepach** [comment]
Hello Oren and Happy New Year. Below is my original code. First I query then I try to add.
Thank you.

---
- hosts: localhost
  gather_facts: false

  vars_files:
    - ./group_vars/credentials.yml

  vars:
    #networkId:  network ID 321
    networkId: network ID 123

  tasks:
    - name: Get all syslog servers
      cisco.meraki.networks_syslog_servers_info:
        meraki_api_key: "{{ my_key }}"
        meraki_suppress_logging: false
        networkId: "{{ networkId }}"
      delegate_to: localhost
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"

    - name: Update syslog settings
      cisco.meraki.networks_syslog_servers:
        meraki_api_key: "{{ my_key }}"
        meraki_suppress_logging: false
        state: present
        networkId: "{{ networkId }}"
        servers:
        - host: 1.2.3.4
          port: 443
          roles:
          - URLs
      delegate_to: localhost
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"
____________________________________

Output
TASK [Get all syslog servers] *************************************************************************************************************************************************************************************
task path: /etc/ansible/update-syslog.yml:14
Read vars_file './group_vars/credentials.yml'
2024-01-01 15:05:20       meraki:     INFO > Meraki dashboard API session initialized with these parameters: {'version': '1.41.0', 'api_key': '****************************************', 'base_url': 'https://api.meraki.com/api/v1', 'single_request_timeout': 60, 'certificate_path': '', 'requests_proxy': '', 'wait_on_rate_limit': True, 'nginx_429_retry_wait_time': 60, 'action_batch_retry_wait_time': 60, 'network_delete_retry_wait_time': 240, 'retry_4xx_error': False, 'retry_4xx_error_wait_time': 60, 'maximum_retries': 2, 'simulate': False, 'be_geo_id': None, 'caller': 'MerakiAnsibleCollection/1.0.0 Cisco', 'use_iterator_for_get_pages': False}
2024-01-01 15:05:20       meraki:     INFO > GET https://api.meraki.com/api/v1/networks/my networkID/syslogServers
2024-01-01 15:05:21       meraki:     INFO > networks, getNetworkSyslogServers - 200 OK
ok: [localhost] => {
    "changed": false,
    "meraki_response": {
        "servers": []
    },
    "result": ""
}
Read vars_file './group_vars/credentials.yml'

TASK [Show result] ************************************************************************************************************************************************************************************************
task path: /etc/ansible/update-syslog.yml:22
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "meraki_response": {
            "servers": []
        },
        "result": ""
    }
}
Read vars_file './group_vars/credentials.yml'

TASK [Update syslog settings] *************************************************************************************************************************************************************************************
task path: /etc/ansible/update-syslog.yml:26
Read vars_file './group_vars/credentials.yml'
The full traceback is:
NoneType: None
fatal: [localhost]: FAILED! => {
    "changed": false,
    "msg": [
        "state. Supported parameters include: meraki_action_batch_retry_wait_time, meraki_api_key, meraki_base_url, meraki_be_geo_id, meraki_certificate_path, meraki_inherit_logging_config, meraki_log_file_prefix, meraki_log_path, meraki_maximum_retries, meraki_nginx_429_retry_wait_time, meraki_output_log, meraki_print_console, meraki_requests_proxy, meraki_retry_4xx_error, meraki_retry_4xx_error_wait_time, meraki_simulate, meraki_single_request_timeout, meraki_suppress_logging, meraki_use_iterator_for_get_pages, meraki_wait_on_rate_limit, networkId, servers."
    ]
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by fabepach** [comment]
Hello Bren, it seems that "state: present" is not needed in the playbook. I ran my script without that statement and it is working.
Thank you.

**Comment by obrigg** [comment]
I’m glad to hear. Happy new year!
