### ISSUE TITLE
deploymentMode is omitted from module even though it is included in module configuration parameters

### ISSUE THREAD

**Issue by fire-ant** [meraki/dashboard-api-ansible#45]
[reference](https://github.com/meraki/dashboard-api-ansible/blob/60bf5676a2e0c8d3014a7656454cd698fe5ac9ca/plugins/modules/networks_cellular_gateway_subnet_pool.py#L69) suggests that Deployment mode should be configurable for a cellular gateway but logging shows the parameter is not an accepted configuration element of the module: 
```
FAILED! => {"changed": false, "msg": ["deploymentMode. Supported parameters include: cidr, mask, meraki_action_batch_retry_wait_time, meraki_api_key, meraki_base_url, meraki_be_geo_id, meraki_certificate_path, meraki_inherit_logging_config, meraki_log_file_prefix, meraki_log_path, meraki_maximum_retries, meraki_nginx_429_retry_wait_time, meraki_output_log, meraki_print_console, meraki_requests_proxy, meraki_retry_4xx_error, meraki_retry_4xx_error_wait_time, meraki_simulate, meraki_single_request_timeout, meraki_suppress_logging, meraki_use_iterator_for_get_pages, meraki_wait_on_rate_limit, networkId, state."]}
```

I think it would be better to correct the documentation in the event the engineering is not possible to support the configuration.

**Comment by obrigg** [comment]
Hello,
Thank you for bringing this to our attention. We'll update the documentation for this module.
