### ISSUE TITLE
Syslog Servers Module documentation lists unsupported parameter, "State"

### ISSUE THREAD

**Issue by tfawbs** [meraki/dashboard-api-ansible#47]
Looking at the documentation for the [cisco.meraki.networks_syslog_servers module](https://docs.ansible.com/ansible/latest/collections/cisco/meraki/networks_syslog_servers_module.html#ansible-collections-cisco-meraki-networks-syslog-servers-module) the example shows to use "state: present".

"state: present" is not a supported parameter for this module and when you include it in a play it fails with an error about it.

Can the documentation for [cisco.meraki.networks_syslog_servers module](https://docs.ansible.com/ansible/latest/collections/cisco/meraki/networks_syslog_servers_module.html#ansible-collections-cisco-meraki-networks-syslog-servers-module) please be updated to remove "state: present" from the example so it is not accidentally copy-pasted by anyone.

**Comment by fmunozmiranda** [comment]
Hi @tfawbs removed from documentation, thank you.
