### ISSUE TITLE
Collection must be made compatible with newly released ansible.utils 4.0.0 ASAP

### ISSUE THREAD

**Issue by felixfontein** [meraki/dashboard-api-ansible#49]
Currently the collection requires ansible.utils < 4.0.0, but ansible.utils 4.0.0 has been released.

This is a violation of the Dependency rules of the Ansible inclusion requirements (https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#collection-dependencies). If this isn't fixed on time, this collection will be removed from Ansible 10 as a consequence.

**Comment by fmunozmiranda** [comment]
Hi @felixfontein, requirements were updated to allow > 4.0.0 ansible.utils, let us know if something else it´s needed

**Comment by felixfontein** [comment]
Assuming that change was part of yesterday's 2.18.0 release, everything should be fine!

**Comment by felixfontein** [comment]
@fmunozmiranda there's one problem: the 2.18.0 release isn't tagged in this repository (which is another requirement). Can you please add a `v2.18.0` tag to the release commit? Thanks :)

**Comment by felixfontein** [comment]
Thanks for pushing the tag! Everything looks good now :)
