### ISSUE TITLE
cisco.meraki.networks_appliance_vlans Multiple problems

### ISSUE THREAD

**Issue by dachaves** [meraki/dashboard-api-ansible#52]
When using the cisco.meraki.networks_appliance_vlans there are two issues:
1. After enabling MX vlans using the module "cisco.meraki.networks_appliance_vlans_settings" and then adding 3 simple vlans to the MX using the "cisco.meraki.networks_appliance_vlans" the MX LAN ports go into Trunk "Drop Untagged traffic". This is easily recreable .

2. The second issue we have is when the vlans are first added, I get the following error, I would expect the Ansible module to first check the existence of the vlan, if it receives a 404, then just create the vlan since the "state" parameter on the task is "Present". 

changed: [localhost] => (item=[{'name': 'New_York'}, {'vlan': 1, 'subnet': '10.1.1.0/24', 'applianceIp': '10.1.1.1', 'vlan_name': 'Management'}])
Error:  An error occured when executing operation.The error was: appliance, getNetworkApplianceVlan - 404 Not Found, please wait a minute if the key or org was just newly created.

3.  In addition, subsequent runs of the same playbook show that the Vlans were "changed" which is not accurate

changed: [localhost] => (item=[{'name': 'New_York'}, {'vlan': 1, 'subnet': '10.1.1.0/24', 'applianceIp': '10.1.1.1', 'vlan_name': 'Management'}])
changed: [localhost] => (item=[{'name': 'New_York'}, {'vlan': 10, 'subnet': '10.1.10.0/24', 'applianceIp': '10.1.10.1', 'vlan_name': 'Data'}])
changed: [localhost] => (item=[{'name': 'New_York'}, {'vlan': 20, 'subnet': '10.1.20.0/24', 'applianceIp': '10.1.20.1', 'vlan_name': 'Voice'}])

**Comment by fmunozmiranda** [comment]
Hi @dachaves please try it with 2.18.1  version of dashboard-api-ansible.

**Comment by fmunozmiranda** [comment]
closed due inactivity

**Comment by dachaves** [comment]
@fmunozmiranda - there were some changes that improve the experience after upgrading to 2.18.1, however, I still get the "The error was: appliance, getNetworkApplianceVlan - 404 Not Found, please wait a minute if the key or org was just newly created." error the first time that I run the playbook. Any chance that this can be resolved?
