### ISSUE TITLE
cisco.meraki.networks_devices_claim Module fails if serial is already claimed

### ISSUE THREAD

**Issue by dachaves** [meraki/dashboard-api-ansible#55]
Re-running networks_devices_claim erros out with the following error : "An exception occurred during task execution. To see the full traceback, use -vvv. The error was: meraki.exceptions.APIError: networks, claimNetworkDevices - 400 Bad Request, {'errors': ['Devices already claimed']}

My expectation with Ansible is that it would check to see if the devices are there, if they are already there, it will simply mark the task as Ok and not try to claim the network again.

Thanks.

**Comment by obrigg** [comment]
Hello,
Thanks for reporting this issue. We are aware of the (lack of) idempotency with the claim operation. Until we address it on the API level, you can use Ansible’s tools to achieve that outcome.
An example: https://github.com/meraki/dashboard-api-ansible/issues/55
