### ISSUE TITLE
meraki_ms_access_policies module has distinct options which are equal

### ISSUE THREAD

**Issue by felixfontein** [meraki/dashboard-api-ansible#57]
The meraki_ms_access_policies module's `net_name` option has the alias `name`, which collides with the option `name`. This looks like an unintentional bug to me.

Ref: https://github.com/ansible/ansible/pull/83530

**Comment by fmunozmiranda** [comment]
meraki_ms_access_policies is deprecated please use cisco.meraki.networks_switch_access_policies instead.
