### ISSUE TITLE
requirements.txt not being introspected correctly by ansible-builder

### ISSUE THREAD

**Issue by djgoosen** [meraki/dashboard-api-ansible#59]
Hi there, it looks like ansible-builder is not correctly introspecting this collection's Python requirements.txt. Comparing with other collections (including cisco.ise as shown below), at a glance it would appear that requirements.txt is potentially being excluded altogether for some reason. I've also tried a few different requirements entries but I cannot make ansible-builder pick up anything in this collection's requirements.txt. Given that the ansible-builder team seems to generally recommend that the Ansible community will use `ansible-builder introspect` to definitively know what the requirements/system dep's are for a given collection at EE build time, I figured it might be good to raise here. 

BTW, Meraki is awesome and Ansible + Meraki is amazing. Please keep the great work coming.

```
[vagrant@rhel9 ~]$ source cmatest/bin/activate
(cmatest) [vagrant@rhel9 ~]$ which ansible-builder 
~/cmatest/bin/ansible-builder
(cmatest) [vagrant@rhel9 ~]$ ansible-builder --version
3.1.0
(cmatest) [vagrant@rhel9 ~]$ mkdir temp_collections
(cmatest) [vagrant@rhel9 ~]$ ansible-galaxy collection install cisco.meraki -p temp_collections/ --force
Starting galaxy collection install process
[WARNING]: The specified collections path '/home/vagrant/temp_collections' is not part of the configured Ansible
collections paths '/home/vagrant/.ansible/collections:/usr/share/ansible/collections'. The installed collection will not
be picked up in an Ansible run, unless within a playbook-adjacent collections directory.
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-meraki-2.18.1.tar.gz to /home/vagrant/.ansible/tmp/ansible-local-4527bwkca0c0/tmprjvf1h7n/cisco-meraki-2.18.1-qt_482wv
Installing 'cisco.meraki:2.18.1' to '/home/vagrant/temp_collections/ansible_collections/cisco/meraki'
cisco.meraki:2.18.1 was installed successfully
'ansible.utils:2.12.0' is already installed, skipping.
(cmatest) [vagrant@rhel9 ~]$ ansible-builder introspect temp_collections/
# Dependency data for temp_collections/
---
python: []
system: []

(cmatest) [vagrant@rhel9 ~]$ ansible-galaxy collection install cisco.ise -p temp_collections/ --force
Starting galaxy collection install process
[WARNING]: The specified collections path '/home/vagrant/temp_collections' is not part of the configured Ansible
collections paths '/home/vagrant/.ansible/collections:/usr/share/ansible/collections'. The installed collection will not
be picked up in an Ansible run, unless within a playbook-adjacent collections directory.
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-ise-2.9.3.tar.gz to /home/vagrant/.ansible/tmp/ansible-local-4744fhsjpqjx/tmpgmfg8sxs/cisco-ise-2.9.3-9hrsifdt
Installing 'cisco.ise:2.9.3' to '/home/vagrant/temp_collections/ansible_collections/cisco/ise'
cisco.ise:2.9.3 was installed successfully
'ansible.utils:2.12.0' is already installed, skipping.
(cmatest) [vagrant@rhel9 ~]$ ansible-builder introspect temp_collections/
# Dependency data for temp_collections/
---
python:
- 'ciscoisesdk >= 2.2.1  # from collection cisco.ise'
- 'requests >= 2.25.1  # from collection cisco.ise'
system: []

(cmatest) [vagrant@rhel9 ~]$ cat temp_collections/ansible_collections/cisco/meraki/requirements.txt && echo
meraki >= 1.33.0
(cmatest) [vagrant@rhel9 ~]$ cat temp_collections/ansible_collections/cisco/ise/requirements.txt
ciscoisesdk >= 2.2.1
requests >= 2.25.1
(cmatest) [vagrant@rhel9 ~]$ 
```

**Comment by djgoosen** [comment]
Digging into this some more, it looks like ansible-builder recommends that "you specify paths to dependency files in the meta/execution-environment.yml file" https://github.com/ansible/ansible-builder/blob/devel/docs/collection_metadata.rst. But it looks like if this defined but doesn't reference those dependencies or file paths, it doesn't look for them. As a quick test, simply removing this collection's meta/execution-environment.yml does lead to the meraki python lib showing up an `ansible-builder introspect`: 

`$ ansible-builder introspect temp_collections/
# Dependency data for temp_collections/
---
python:
  cisco.meraki:
  - meraki
  vmware.vmware_rest:
  - aiohttp
system:
  vmware.vmware_rest:
  - gcc [compile platform:centos-8 platform:rhel-8]
  - gcc [compile platform:rhel-9]

$`

Not sure what the "best" path forward might be here, but it does seem like this collection is potentially structured in a way that doesn't entirely conform to current community guidance around distributing collections? I don't see anything here on this but might be worth a deeper review: https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_distributing.html

**Comment by fmunozmiranda** [comment]
Hi, are you referring to the requirements structure within meta/? @djgoosen 
Thank you for your feedback.

**Comment by djgoosen** [comment]
Hi, @fmunozmiranda yes, if you take a look at the way `ansible-builder introspect` appears to process a given collection, if it finds meta/execution-environment.yml, it seems like it either finds that this file is directing it to locations like an underlying Python requirements.txt file path for further processing; or it apparently decides that there must be no Python dependencies, etc. for this collection and it stops introspecting. Only if it DOESN'T find meta/execution-environment.yml, will it then look for files like requirements.txt in the base file path. I don't know if this is how things "should" work according to current Ansible community guidance, etc. but it seems to be the way that it does work.

https://github.com/ansible/ansible-builder/blob/devel/src/ansible_builder/_target_scripts/introspect.py

**Comment by fmunozmiranda** [comment]
Does it seem correct to you this way? @djgoosen

**Comment by djgoosen** [comment]
@fmunozmiranda respectfully, no this collection's meta/ contents do not seem "correct" to me this way, based on the de facto "standard" that others who are maintaining similar Ansible collections seem to be going about it today. 

If I were to make a recommendation, I would suggest either aligning this project's `meta/execution-environment.yml` to what ansible-builder [appears to be expecting](https://github.com/ansible/ansible-builder/blob/devel/docs/collection_metadata.rst#collection-level-dependencies); or perhaps simply removing the `meta/execution-environment.yml` file from this project, similar to what a number of other projects, including [Cisco ISE Ansible](https://github.com/CiscoISE/ansible-ise/tree/main/meta) and [Palo Ansible](https://github.com/PaloAltoNetworks/pan-os-ansible/tree/develop/meta) seem to be functioning OK without. Thank you.
