### ISSUE TITLE
cisco.meraki.networks_devices_claim - got an unexpected keyword argument 'network_id'

### ISSUE THREAD

**Issue by benjamincash89** [meraki/dashboard-api-ansible#6]
When using the cisco.meraki.networks_devices_claim and passing the networkId and serials parameters it fails with the below output.

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Networks.claimNetworkDevices() got an unexpected keyword argument 'network_id'
fatal: [9998_bc_test]: FAILED! => {"msg": "Unexpected failure during module execution: Networks.claimNetworkDevices() got an unexpected keyword argument 'network_id'", "stdout": ""}

**Comment by fmunozmiranda** [comment]
Hi @benjamincash89 , could you retry it again, bug was in parameter naming, thanks for reporting, if it works for you, feel free to close the issue.

**Comment by benjamincash89** [comment]
I'll test and confirm shortly! Thanks

**Comment by benjamincash89** [comment]
Yeah it works as expected now. Thank you!
