### ISSUE TITLE
cisco.meraki.networks_clients_info  - incorrect API endpoint

### ISSUE THREAD

**Issue by imanassypov** [meraki/dashboard-api-ansible#64]
This module is referencing an incorrect API endpoint.
Instead of expected /networks/{networkId}/clients/ it uses the more specific /networks/{networkId}/clients/{clientId} (which also overlaps with the adjacent module for cisco.meraki.networks_client_info)

https://docs.ansible.com/ansible/latest/collections/cisco/meraki/networks_clients_info_module.html#ansible-collections-cisco-meraki-networks-clients-info-module

**Comment by fmunozmiranda** [comment]
closed due inactivity
