### ISSUE TITLE
cisco.meraki.networks_appliance_content_filtering module

### ISSUE THREAD

**Issue by loopwert** [meraki/dashboard-api-ansible#8]
This module does not have a query mode to pull the current state of the content filtering. I think this would be useful to check the config to update the config instead of blowing away the whole current config.

**Comment by obrigg** [comment]
Can you kindly try using the cisco.meraki.networks_appliance_content_filtering_info module?

**Comment by loopwert** [comment]
Sorry i swear looked through all of them
