### ISSUE TITLE
networks_switch_access_policies: does not option to create a policy

### ISSUE THREAD

**Issue by y0rune** [meraki/dashboard-api-ansible#9]
Hello!
In the module `cisco.meraki.networks_switch_access_policies` I do not find the `Set` / `Create` Option (https://github.com/meraki/dashboard-api-ansible/blob/main/plugins/modules/networks_switch_access_policies_info.py#L12-L13). In my module `meraki_ms_access_policies` I added the create option. May I help with that module?

**Comment by obrigg** [comment]
Hi Marcin,
Did you try the `cisco.meraki.networks_switch_access_policies` module?

**Comment by jbogarin** [comment]
@y0rune there are two different modules:
- [networks_switch_access_policies](https://docs.ansible.com/ansible/latest/collections/cisco/meraki/networks_switch_access_policies_module.html#ansible-collections-cisco-meraki-networks-switch-access-policies-module)
- [networks_switch_access_policies_info](https://docs.ansible.com/ansible/latest/collections/cisco/meraki/networks_switch_access_policies_info_module.html#ansible-collections-cisco-meraki-networks-switch-access-policies-info-module)

Overall, it's the same in all the collection. We have an _info module to get information and then another module to create, update and delete. We did it following recommendations from the Red Hat team.

The `networks_switch_access_policies` should allow you to create as you need to.

**Comment by y0rune** [comment]
All right thank you!
